# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/google/GSearch.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/google/GSearch.ipynb 2
from typing import List
from dataclasses import dataclass, field
import gdoc_sync.client as gd
import httpx

from nbdev.showdoc import patch_to
