# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gdoc_sync',
                'doc_host': 'https://jaewilson07.github.io',
                'git_url': 'https://github.com/jaewilson07/gdoc_sync',
                'lib_path': 'gdoc_sync'},
  'syms': {'gdoc_sync.core': {'gdoc_sync.core.foo': ('core.html#foo', 'gdoc_sync/core.py')}}}
