# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gdoc_sync',
                'doc_host': 'https://jaewilson07.github.io',
                'git_url': 'https://github.com/jaewilson07/gdoc_sync',
                'lib_path': 'gdoc_sync'},
  'syms': { 'gdoc_sync.creds': { 'gdoc_sync.creds.GenerateTokenFile_RequiresClientInfo': ( 'creds.html#generatetokenfile_requiresclientinfo',
                                                                                           'gdoc_sync/creds.py'),
                                 'gdoc_sync.creds.GenerateTokenFile_RequiresClientInfo.__init__': ( 'creds.html#generatetokenfile_requiresclientinfo.__init__',
                                                                                                    'gdoc_sync/creds.py'),
                                 'gdoc_sync.creds.generate_creds_object': ('creds.html#generate_creds_object', 'gdoc_sync/creds.py'),
                                 'gdoc_sync.creds.generate_token_from_oauth_with_client_info': ( 'creds.html#generate_token_from_oauth_with_client_info',
                                                                                                 'gdoc_sync/creds.py')},
            'gdoc_sync.drive': { 'gdoc_sync.drive.GoogleDrive_MimeType_Enum': ( 'drive.html#googledrive_mimetype_enum',
                                                                                'gdoc_sync/drive.py'),
                                 'gdoc_sync.drive.get_file_looper': ('drive.html#get_file_looper', 'gdoc_sync/drive.py'),
                                 'gdoc_sync.drive.get_files': ('drive.html#get_files', 'gdoc_sync/drive.py'),
                                 'gdoc_sync.drive.process_file': ('drive.html#process_file', 'gdoc_sync/drive.py')}}}
