# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/gdoc_sync",
        "doc_host": "https://jaewilson07.github.io",
        "git_url": "https://github.com/jaewilson07/gdoc_sync",
        "lib_path": "gdoc_sync",
    },
    "syms": {
        "gdoc_sync.asana.auth": {
            "gdoc_sync.asana.auth.AsanaAuth": (
                "asana/auth.html#asanaauth",
                "gdoc_sync/asana/auth.py",
            ),
            "gdoc_sync.asana.auth.AsanaAuth.__post_init__": (
                "asana/auth.html#asanaauth.__post_init__",
                "gdoc_sync/asana/auth.py",
            ),
            "gdoc_sync.asana.auth.AsanaAuth.generate_auth_header": (
                "asana/auth.html#asanaauth.generate_auth_header",
                "gdoc_sync/asana/auth.py",
            ),
            "gdoc_sync.asana.auth.AsanaAuth.get_auth_token": (
                "asana/auth.html#asanaauth.get_auth_token",
                "gdoc_sync/asana/auth.py",
            ),
        },
        "gdoc_sync.asana.project": {
            "gdoc_sync.asana.project.AsanaMembership": (
                "asana/project.html#asanamembership",
                "gdoc_sync/asana/project.py",
            ),
            "gdoc_sync.asana.project.AsanaMembership._from_json": (
                "asana/project.html#asanamembership._from_json",
                "gdoc_sync/asana/project.py",
            ),
            "gdoc_sync.asana.project.AsanaMembership.to_text": (
                "asana/project.html#asanamembership.to_text",
                "gdoc_sync/asana/project.py",
            ),
            "gdoc_sync.asana.project.AsanaProject": (
                "asana/project.html#asanaproject",
                "gdoc_sync/asana/project.py",
            ),
            "gdoc_sync.asana.project.AsanaProject._from_json": (
                "asana/project.html#asanaproject._from_json",
                "gdoc_sync/asana/project.py",
            ),
            "gdoc_sync.asana.project.AsanaProject.get_by_id": (
                "asana/project.html#asanaproject.get_by_id",
                "gdoc_sync/asana/project.py",
            ),
            "gdoc_sync.asana.project.AsanaProject.get_projects": (
                "asana/project.html#asanaproject.get_projects",
                "gdoc_sync/asana/project.py",
            ),
            "gdoc_sync.asana.project.AsanaSection": (
                "asana/project.html#asanasection",
                "gdoc_sync/asana/project.py",
            ),
            "gdoc_sync.asana.project.AsanaSection._from_json": (
                "asana/project.html#asanasection._from_json",
                "gdoc_sync/asana/project.py",
            ),
        },
        "gdoc_sync.asana.task": {
            "gdoc_sync.asana.task.AsanaMembership": (
                "asana/task.html#asanamembership",
                "gdoc_sync/asana/task.py",
            ),
            "gdoc_sync.asana.task.AsanaMembership._from_json": (
                "asana/task.html#asanamembership._from_json",
                "gdoc_sync/asana/task.py",
            ),
            "gdoc_sync.asana.task.AsanaMembership.to_text": (
                "asana/task.html#asanamembership.to_text",
                "gdoc_sync/asana/task.py",
            ),
            "gdoc_sync.asana.task.AsanaSection": (
                "asana/task.html#asanasection",
                "gdoc_sync/asana/task.py",
            ),
            "gdoc_sync.asana.task.AsanaSection._from_json": (
                "asana/task.html#asanasection._from_json",
                "gdoc_sync/asana/task.py",
            ),
            "gdoc_sync.asana.task.AsanaStory": (
                "asana/task.html#asanastory",
                "gdoc_sync/asana/task.py",
            ),
            "gdoc_sync.asana.task.AsanaStory._from_json": (
                "asana/task.html#asanastory._from_json",
                "gdoc_sync/asana/task.py",
            ),
            "gdoc_sync.asana.task.AsanaStory.to_text": (
                "asana/task.html#asanastory.to_text",
                "gdoc_sync/asana/task.py",
            ),
            "gdoc_sync.asana.task.AsanaTask": (
                "asana/task.html#asanatask",
                "gdoc_sync/asana/task.py",
            ),
            "gdoc_sync.asana.task.AsanaTask._from_json": (
                "asana/task.html#asanatask._from_json",
                "gdoc_sync/asana/task.py",
            ),
            "gdoc_sync.asana.task.AsanaTask.get_by_id": (
                "asana/task.html#asanatask.get_by_id",
                "gdoc_sync/asana/task.py",
            ),
            "gdoc_sync.asana.task.AsanaTask.get_stories": (
                "asana/task.html#asanatask.get_stories",
                "gdoc_sync/asana/task.py",
            ),
            "gdoc_sync.asana.task.AsanaTask.to_md": (
                "asana/task.html#asanatask.to_md",
                "gdoc_sync/asana/task.py",
            ),
            "gdoc_sync.asana.task.ap.AsanaProject.get_tasks": (
                "asana/task.html#ap.asanaproject.get_tasks",
                "gdoc_sync/asana/task.py",
            ),
        },
        "gdoc_sync.asana.user": {
            "gdoc_sync.asana.user.AsanaUser": (
                "asana/user.html#asanauser",
                "gdoc_sync/asana/user.py",
            ),
            "gdoc_sync.asana.user.AsanaUser._from_json": (
                "asana/user.html#asanauser._from_json",
                "gdoc_sync/asana/user.py",
            ),
            "gdoc_sync.asana.user.AsanaUser.get_by_id": (
                "asana/user.html#asanauser.get_by_id",
                "gdoc_sync/asana/user.py",
            ),
        },
        "gdoc_sync.client": {
            "gdoc_sync.client.Auth": ("client/client.html#auth", "gdoc_sync/client.py"),
            "gdoc_sync.client.Auth.auth_header": (
                "client/client.html#auth.auth_header",
                "gdoc_sync/client.py",
            ),
            "gdoc_sync.client.Auth.generate_auth_header": (
                "client/client.html#auth.generate_auth_header",
                "gdoc_sync/client.py",
            ),
            "gdoc_sync.client.ResponseGetData": (
                "client/client.html#responsegetdata",
                "gdoc_sync/client.py",
            ),
            "gdoc_sync.client.ResponseGetData.__post_init__": (
                "client/client.html#responsegetdata.__post_init__",
                "gdoc_sync/client.py",
            ),
            "gdoc_sync.client.ResponseGetData._from_cache": (
                "client/client.html#responsegetdata._from_cache",
                "gdoc_sync/client.py",
            ),
            "gdoc_sync.client.ResponseGetData._from_httpx": (
                "client/client.html#responsegetdata._from_httpx",
                "gdoc_sync/client.py",
            ),
            "gdoc_sync.client.get_cache": (
                "client/client.html#get_cache",
                "gdoc_sync/client.py",
            ),
            "gdoc_sync.client.get_data": (
                "client/client.html#get_data",
                "gdoc_sync/client.py",
            ),
            "gdoc_sync.client.looper": (
                "client/client.html#looper",
                "gdoc_sync/client.py",
            ),
            "gdoc_sync.client.prepare_fetch": (
                "client/client.html#prepare_fetch",
                "gdoc_sync/client.py",
            ),
            "gdoc_sync.client.update_cache": (
                "client/client.html#update_cache",
                "gdoc_sync/client.py",
            ),
        },
        "gdoc_sync.google.auth": {
            "gdoc_sync.google.auth.GoogleAuth": (
                "google/auth.html#googleauth",
                "gdoc_sync/google/auth.py",
            ),
            "gdoc_sync.google.auth.GoogleAuth._new_token_via_auth_flow": (
                "google/auth.html#googleauth._new_token_via_auth_flow",
                "gdoc_sync/google/auth.py",
            ),
            "gdoc_sync.google.auth.GoogleAuth._refresh_token": (
                "google/auth.html#googleauth._refresh_token",
                "gdoc_sync/google/auth.py",
            ),
            "gdoc_sync.google.auth.GoogleAuth.generate_service": (
                "google/auth.html#googleauth.generate_service",
                "gdoc_sync/google/auth.py",
            ),
            "gdoc_sync.google.auth.GoogleAuth.get_creds_from_env": (
                "google/auth.html#googleauth.get_creds_from_env",
                "gdoc_sync/google/auth.py",
            ),
            "gdoc_sync.google.auth.GoogleAuth.get_creds_from_file": (
                "google/auth.html#googleauth.get_creds_from_file",
                "gdoc_sync/google/auth.py",
            ),
            "gdoc_sync.google.auth.GoogleAuth_NoEnv_Error": (
                "google/auth.html#googleauth_noenv_error",
                "gdoc_sync/google/auth.py",
            ),
            "gdoc_sync.google.auth.GoogleAuth_NoEnv_Error.__init__": (
                "google/auth.html#googleauth_noenv_error.__init__",
                "gdoc_sync/google/auth.py",
            ),
        },
        "gdoc_sync.google.converter": {
            "gdoc_sync.google.converter.GoogleDrive_MimeType_Enum": (
                "google/drive_converter.html#googledrive_mimetype_enum",
                "gdoc_sync/google/converter.py",
            ),
            "gdoc_sync.google.converter.ImageBlockConverter": (
                "google/drive_converter.html#imageblockconverter",
                "gdoc_sync/google/converter.py",
            ),
            "gdoc_sync.google.converter.ImageBlockConverter.convert_img": (
                "google/drive_converter.html#imageblockconverter.convert_img",
                "gdoc_sync/google/converter.py",
            ),
            "gdoc_sync.google.converter.clean_bs4": (
                "google/drive_converter.html#clean_bs4",
                "gdoc_sync/google/converter.py",
            ),
            "gdoc_sync.google.converter.convert_file_in_place": (
                "google/drive_converter.html#convert_file_in_place",
                "gdoc_sync/google/converter.py",
            ),
            "gdoc_sync.google.converter.download_pptx": (
                "google/drive_converter.html#download_pptx",
                "gdoc_sync/google/converter.py",
            ),
            "gdoc_sync.google.converter.download_zip": (
                "google/drive_converter.html#download_zip",
                "gdoc_sync/google/converter.py",
            ),
            "gdoc_sync.google.converter.md": (
                "google/drive_converter.html#md",
                "gdoc_sync/google/converter.py",
            ),
        },
        "gdoc_sync.google.drive": {
            "gdoc_sync.google.drive.GDocFile_DownloadError": (
                "google/drive.html#gdocfile_downloaderror",
                "gdoc_sync/google/drive.py",
            ),
            "gdoc_sync.google.drive.GDocFile_DownloadError.__init__": (
                "google/drive.html#gdocfile_downloaderror.__init__",
                "gdoc_sync/google/drive.py",
            ),
            "gdoc_sync.google.drive.GDoc_File": (
                "google/drive.html#gdoc_file",
                "gdoc_sync/google/drive.py",
            ),
            "gdoc_sync.google.drive.GDoc_File.__post_init__": (
                "google/drive.html#gdoc_file.__post_init__",
                "gdoc_sync/google/drive.py",
            ),
            "gdoc_sync.google.drive.GDoc_File._from_json": (
                "google/drive.html#gdoc_file._from_json",
                "gdoc_sync/google/drive.py",
            ),
            "gdoc_sync.google.drive.GDoc_File.download_file": (
                "google/drive.html#gdoc_file.download_file",
                "gdoc_sync/google/drive.py",
            ),
            "gdoc_sync.google.drive.GDoc_File.get_content": (
                "google/drive.html#gdoc_file.get_content",
                "gdoc_sync/google/drive.py",
            ),
            "gdoc_sync.google.drive.GDoc_File.get_from_id": (
                "google/drive.html#gdoc_file.get_from_id",
                "gdoc_sync/google/drive.py",
            ),
            "gdoc_sync.google.drive.GoogleDrive_MimeType_Enum": (
                "google/drive.html#googledrive_mimetype_enum",
                "gdoc_sync/google/drive.py",
            ),
        },
        "gdoc_sync.google.looper": {
            "gdoc_sync.google.looper.GDoc_Files": (
                "google/looper.html#gdoc_files",
                "gdoc_sync/google/looper.py",
            ),
            "gdoc_sync.google.looper.GDoc_Files.__post_init__": (
                "google/looper.html#gdoc_files.__post_init__",
                "gdoc_sync/google/looper.py",
            ),
            "gdoc_sync.google.looper.GDoc_Files._get_folder_contents": (
                "google/looper.html#gdoc_files._get_folder_contents",
                "gdoc_sync/google/looper.py",
            ),
            "gdoc_sync.google.looper.GDoc_Files.get_files": (
                "google/looper.html#gdoc_files.get_files",
                "gdoc_sync/google/looper.py",
            ),
        },
        "gdoc_sync.integrations.ProxyCurl": {
            "gdoc_sync.integrations.ProxyCurl.ProxyCurlAuth": (
                "integrations/proxycurl.html#proxycurlauth",
                "gdoc_sync/integrations/ProxyCurl.py",
            ),
            "gdoc_sync.integrations.ProxyCurl.ProxyCurlAuth.get_auth_headers": (
                "integrations/proxycurl.html#proxycurlauth.get_auth_headers",
                "gdoc_sync/integrations/ProxyCurl.py",
            ),
            "gdoc_sync.integrations.ProxyCurl.get_linked_in_profile_route": (
                "integrations/proxycurl.html#get_linked_in_profile_route",
                "gdoc_sync/integrations/ProxyCurl.py",
            ),
            "gdoc_sync.integrations.ProxyCurl.scrape_linkedin_profile": (
                "integrations/proxycurl.html#scrape_linkedin_profile",
                "gdoc_sync/integrations/ProxyCurl.py",
            ),
        },
        "gdoc_sync.jira.routes": {
            "gdoc_sync.jira.routes.get_boards": (
                "routes.html#get_boards",
                "gdoc_sync/jira/routes.py",
            )
        },
        "gdoc_sync.utils": {
            "gdoc_sync.utils.ImageBlockConverter": (
                "client/utils.html#imageblockconverter",
                "gdoc_sync/utils.py",
            ),
            "gdoc_sync.utils.ImageBlockConverter.convert_img": (
                "client/utils.html#imageblockconverter.convert_img",
                "gdoc_sync/utils.py",
            ),
            "gdoc_sync.utils.convert_html_to_markdown": (
                "client/utils.html#convert_html_to_markdown",
                "gdoc_sync/utils.py",
            ),
            "gdoc_sync.utils.convert_str_file_name": (
                "client/utils.html#convert_str_file_name",
                "gdoc_sync/utils.py",
            ),
            "gdoc_sync.utils.convert_str_keep_alphanumeric": (
                "client/utils.html#convert_str_keep_alphanumeric",
                "gdoc_sync/utils.py",
            ),
            "gdoc_sync.utils.convert_str_remove_accents": (
                "client/utils.html#convert_str_remove_accents",
                "gdoc_sync/utils.py",
            ),
            "gdoc_sync.utils.convert_str_to_date": (
                "client/utils.html#convert_str_to_date",
                "gdoc_sync/utils.py",
            ),
            "gdoc_sync.utils.convert_str_to_snake_case": (
                "client/utils.html#convert_str_to_snake_case",
                "gdoc_sync/utils.py",
            ),
            "gdoc_sync.utils.download_pptx": (
                "client/utils.html#download_pptx",
                "gdoc_sync/utils.py",
            ),
            "gdoc_sync.utils.download_zip": (
                "client/utils.html#download_zip",
                "gdoc_sync/utils.py",
            ),
            "gdoc_sync.utils.md": ("client/utils.html#md", "gdoc_sync/utils.py"),
            "gdoc_sync.utils.update_env": (
                "client/utils.html#update_env",
                "gdoc_sync/utils.py",
            ),
            "gdoc_sync.utils.upsert_folder": (
                "client/utils.html#upsert_folder",
                "gdoc_sync/utils.py",
            ),
        },
    },
}
