# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% ../nbs/utils.ipynb 2
from __future__ import annotations

import datetime as dt
from dateutil.parser import parse as dtu_parse

from nbdev.showdoc import show_doc

# %% auto 0
__all__ = ['get_date']

# %% ../nbs/utils.ipynb 3
def get_date(datefield: str) -> dt.datetime:
    """Returns a datetime object from a date field"""
    return dtu_parse(datefield) if datefield else None
