name: import_google

on:
  push:
    branches: [ "main", "master" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        credentials_json: '${{ secrets.GCP_KEY }}'
        access_token_scopes: 'https://www.googleapis.com/auth/drive'
        
    - uses: r7kamura/google-docs-to-github@v3
      with:
        google_drive_folder_id: 1VyzBe-sJCDujP6D6dok7Za-u_syXpfdU
