name: import_google

on:
  push:
    branches: [ "main", "master" ]

env:
  GOOGLE_APPLICATION_CREDENTIALS : ${{ secrets.GCP_KEY}}

jobs:
  publish:
    runs-on: ubuntu-latest
    
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: r7kamura/google-docs-to-github@v3
      with:
        google_drive_folder_id: 1VyzBe-sJCDujP6D6dok7Za-u_syXpfdU
